services:
  postgres:
    container_name: "media_postgres"
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: media_approval
    volumes:
      - "media_database_data:/bitnami/postgresql"

  postgres-test:
    container_name: "media_postgres_test"
    image: "bitnami/postgresql:latest"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres_test
      POSTGRES_PASSWORD: docker_test
      POSTGRES_DB: media_approval_test

  redis:
    container_name: media_redis
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=docker
    volumes:
      - media_redis_data:/data

volumes:
  media_database_data:
  media_redis_data:
